### ISSUE TITLE
Cannot find zero-clipboard component

### ISSUE THREAD

**Issue by sunocean-sand** [aomran/ember-cli-zero-clipboard#15]
My ember app can't find the zero-clipboard component for some reason.

Am I missing something in the installation steps? It's included in my package.json and I used -save--dev during installation.

**Comment by aomra015** [comment]
sorry I can't help without more context. can you provide the error and version numbers?

**Comment by nruth** [comment]
"ember-cli": "0.2.6",
"ember": "1.12.0"

Uncaught Error: Assertion Failed: A helper named 'zero-clipboard' could not be found

**Comment by nruth** [comment]
Please ignore my previous comment, I npm installed to the wrong path. It does work fine with those versions.
